name: docker-build

on:
  workflow_dispatch:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
env:
  FOLDER: ols-dockerfiles/template
  OLS_VERSION: 1.8.2

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        PHP_VERSION: [lsphp81,lsphp82,lsphp83]
        TAG: [latest,'']
    steps:
      - uses: actions/checkout@v2
      - name: Docker build and push
        if: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch') }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          cd ${{ env.FOLDER }}
          bash build.sh --ols ${{ env.OLS_VERSION }} --php ${{ matrix.PHP_VERSION }} --tag "${{ matrix.TAG }}" --push
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'pull_request' }}
        run: |
          cd ${{ env.FOLDER }}
          bash build.sh --ols ${{ env.OLS_VERSION }} --php ${{ matrix.PHP_VERSION }} --tag ${{ matrix.TAG }}            

  